name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 17 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: MikePopoloski/slang
        path: slang
    - name: Configure and build slang
      working-directory: slang
      run: cmake -B build && cmake --build build -j8
    - name: Install slang
      working-directory: slang
      run: sudo cmake --install build --component slang_Development --strip --prefix
    - name: Configure and build test project
      run: cmake -B build && cmake --build build -j8